name: Metric and Commit Results

on:
  workflow_dispatch:     # Allows manual triggering of the workflow

jobs:
  compile-time:
    name: Compile Time
    runs-on: ubuntu-latest
    # if: ${{ github.ref_name == 'main' }}
    outputs:
      time: ${{ steps.run.outputs.COMPILE_TIME }}
    steps:
      - uses: taiki-e/checkout-action@v1
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: Boshen/setup-rust@main
      - run: cargo clean # build from scatch using local system cache to avoid download from crates.io
      - id: run
        run: |
          /usr/bin/time -f "%e" -o output cargo build --release
          cat output
          COMPILE_TIME=$(cat output)
          echo $COMPILE_TIME
          echo "COMPILE_TIME=$COMPILE_TIME" >> $GITHUB_OUTPUT

  metric:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rolldown metric repository
        uses: actions/checkout@v4
        with:
          repository: 'rolldown/metric'
          ref: 'main'
          token:  ${{ secrets.METRIC_SECRET_KEY }}


      - name: Commit benchmark results
        run: |
          echo 'test' >> metric.json
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add metric.json
          git commit -m "Update benchmark results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
